# Generated by Django 2.2.7 on 2019-11-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_picker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ghost_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghost_name', models.CharField(max_length=256)),
                ('descripton', models.CharField(max_length=256)),
            ],
        ),
    ]
