# Generated by Django 2.2.7 on 2019-11-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('name_picker', '0002_ghost_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghost_names',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='name_picker.ghost_user'),
        ),
    ]
